name: AI Meme Bot

on:
  workflow_dispatch:  # Позволяет ручной запуск с кнопки
  schedule:
    - cron: "0 */6 * * *"  # Автоматический запуск каждые 6 часов

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install tweepy openai requests pillow

      - name: Run bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python meme_bot.py
        
